import Head from 'next/head'
import{motion as m} from 'framer-motion';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Happy Pickle</h1>
        </div>
      </main>
    </div>
  )
}
